import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { type Address, type Hex } from 'viem';
import { createReader, getCanonicalPool, tokenName, type NetworkConfig } from '../sdk/canonicalPool.js';
const raw = JSON.parse(readFileSync('deployments/local.json','utf8')) as NetworkConfig & { token: Address; poolId: Hex };
const config = { ...raw, chainId: BigInt(raw.chainId) };
const client = createReader(process.env.RPC_URL ?? 'http://127.0.0.1:18545');
const result = await getCanonicalPool(client,config,raw.token);
assert.equal(result.status,'registered');
if(result.status!=='registered') throw Error('Missing canonical pool');
assert.deepEqual({...result,key:undefined},{ status:'registered',source:'ens',chainId:31337n,poolManager:raw.poolManager,poolId:raw.poolId,key:undefined });
const missing = await getCanonicalPool(client,config,'0x0000000000000000000000000000000000000123');
assert.deepEqual(missing,{status:'not_registered'});
const broken = await getCanonicalPool(client,{...config,resolverImplementation:'0x0000000000000000000000000000000000000123'},raw.token);
assert.deepEqual(broken,{status:'lookup_failed',reason:'namespace'});
console.log(JSON.stringify({ name:tokenName(raw.token), poolId:raw.poolId, checks:['viem getEnsText -> registered','empty wildcard record -> not_registered','implementation mismatch -> lookup_failed'] },null,2));
